import Link from 'next/link';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Container from '@/components/ui/Container';
import LegalContactDetails from '@/components/LegalContactDetails';

export const metadata = {
  title: 'Privacy Policy | LAHIT Animal Welfare',
  description: 'How LAHIT Animal Welfare collects, uses, stores and protects personal information.',
};

const sections = [
  ['1. Who we are', <><p>LAHIT Animal Welfare is a volunteer-led animal rescue initiative working across Uttarakhand, India. In this policy, “LAHIT”, “we”, “us” and “our” mean LAHIT Animal Welfare. This website is available at <span className="font-semibold">lahitanimalwelfare.org</span> and its related pages and services.</p><p>We are not a registered NGO at this time. This policy explains how information submitted through this website is handled by our team and the service providers that help us operate it.</p></>],
  ['2. Information we collect', <><p>Depending on how you use the website, we may receive:</p><ul><li><strong>Rescue reports:</strong> your name, phone number, animal type, location, description of the animal’s condition and an optional photograph.</li><li><strong>Adoption applications:</strong> your name, email, phone number, city or location, home type, previous pet experience, message and the animal you selected.</li><li><strong>Volunteer applications:</strong> your name, email, phone number, interests, availability, location and any message you choose to submit.</li><li><strong>Candidate or workspace accounts:</strong> your name, email address, password credentials and profile or application information. Passwords are stored in protected, hashed form rather than as plain text.</li><li><strong>Images and media:</strong> images you upload for rescue reports or that authorised administrators add to the public website.</li><li><strong>Technical information:</strong> limited information that may be recorded by our hosting, security and email providers, such as browser, device, IP address, timestamps and error logs.</li></ul><p>Please do not submit another person’s personal information or a photograph of a person without having a lawful basis or permission to do so.</p></>],
  ['3. Why we use information', <><p>We use information only as reasonably necessary to:</p><ul><li>review and respond to animal rescue reports;</li><li>assess adoption and volunteer applications and contact you about next steps;</li><li>create and manage authorised candidate or administrative accounts;</li><li>send password-reset codes, service messages and replies to enquiries;</li><li>publish and manage animal, rescue, blog and impact information;</li><li>keep the website, records and accounts secure and prevent misuse; and</li><li>meet legal, regulatory, accounting or safeguarding obligations where applicable.</li></ul><p>We do not sell personal information or use rescue, adoption or volunteer submissions for targeted advertising.</p></>],
  ['4. Sharing and service providers', <><p>Access is limited to LAHIT team members and volunteers who need it for rescue, adoption, volunteer coordination, administration or support. We may also use trusted providers for hosting, database storage, authentication, image storage and delivery, transactional email and website security.</p><p>These providers may process information on our behalf and may operate from locations outside Uttarakhand or India. We do not authorise them to use your information for their own advertising. We may disclose information where required by law, to protect people or animals, or to investigate fraud, abuse or security incidents.</p></>],
  ['5. Images, public content and third-party links', <><p>Images, rescue stories, animal profiles and blog content published on the website may be visible to the public. Do not upload a photograph if it contains sensitive personal information that you do not want shared. If you believe an image or story identifies you improperly, contact us and we will review the request.</p><p>The website may link to social media, maps, messaging services or other third-party websites. Their own privacy policies apply when you leave our website or use those services.</p></>],
  ['6. Retention and security', <><p>We keep information for as long as reasonably needed for the purpose for which it was collected, ongoing animal welfare records, account administration, dispute handling, safety and legal obligations. When it is no longer needed, we aim to delete it or make it non-identifying, subject to backups and legal requirements.</p><p>We use access controls, authentication, encrypted connections and provider security features appropriate to the information we hold. No online service can guarantee absolute security, so please avoid sending unnecessary sensitive information through forms or email.</p></>],
  ['7. Your choices and requests', <><p>You may ask us to access, correct, update or delete personal information that you submitted, or ask us to stop contacting you for a particular purpose. Some records may need to be retained for safety, legal or operational reasons. We may ask for reasonable verification before acting on a request.</p><p>We will try to respond within a reasonable period and explain if a request cannot be fully completed.</p></>],
  ['8. Children and emergencies', <><p>The website is not intended to collect information from children independently. A parent or guardian should supervise any application or report submitted by a minor.</p><p>This website is not an emergency service and submitting a form does not guarantee immediate assistance. For an urgent or life-threatening situation, contact the appropriate local emergency, veterinary or animal-control service first.</p></>],
  ['9. Changes and contact', <><p>We may update this policy when our services, providers or legal obligations change. The updated version will be posted on this page with a new “Last updated” date.</p><LegalContactDetails /></>],
];

function LegalSections() {
  return <div className="space-y-8 rounded-[2rem] border border-primary/10 bg-base-100 p-6 shadow-[0_12px_50px_rgba(11,51,36,0.06)] sm:p-10">{sections.map(([title, body]) => <section key={title} className="border-b border-primary/10 pb-8 last:border-b-0 last:pb-0"><h2 className="text-2xl font-black tracking-[-0.035em] text-primary">{title}</h2><div className="mt-4 space-y-4 leading-relaxed text-primary/70 [&_li]:ml-5 [&_li]:list-disc [&_ul]:space-y-2">{body}</div></section>)}</div>;
}

export default function PrivacyPolicyPage() {
  return <main className="public-page min-h-screen bg-base-200"><Navbar /><section className="pt-32 pb-16 sm:pt-40 sm:pb-24"><Container size="md"><div className="mb-12 max-w-3xl"><span className="eyebrow text-secondary">Your information matters</span><h1 className="mt-6 text-4xl font-black tracking-[-0.055em] text-primary sm:text-6xl">Privacy Policy</h1><p className="mt-5 text-lg leading-relaxed text-primary/65">A plain-language explanation of how LAHIT handles information submitted through this website.</p><p className="mt-4 text-sm font-semibold uppercase tracking-[0.1em] text-primary/45">Last updated: 22 September 2026</p></div><LegalSections /><p className="mt-8 text-sm leading-relaxed text-primary/50">This page is a website policy draft based on the features currently present in the LAHIT application. It is not legal advice and should be reviewed with a qualified professional before publication.</p><Link href="/" className="mt-6 inline-flex font-bold text-primary underline decoration-primary/25 underline-offset-4">← Back to LAHIT</Link></Container></section><Footer /></main>;
}
