import Link from 'next/link';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Container from '@/components/ui/Container';
import LegalContactDetails from '@/components/LegalContactDetails';

export const metadata = {
  title: 'Terms of Service | LAHIT Animal Welfare',
  description: 'Terms that apply when you use the LAHIT Animal Welfare website and services.',
};

const sections = [
  ['1. About these terms', <><p>These Terms of Service govern your use of the LAHIT Animal Welfare website, including its public pages, rescue reporting, adoption and volunteer forms, blogs, candidate area and administrative workspace.</p><p>By using the website, you agree to these terms and our <Link className="font-semibold underline decoration-primary/25 underline-offset-4" href="/privacy/">Privacy Policy</Link>. If you do not agree, please do not use the website.</p></>],
  ['2. Our role', <><p>LAHIT is a volunteer-led animal rescue initiative working across Uttarakhand, India. We are not a registered NGO at this time. The website helps us share information, receive reports and applications, coordinate volunteers and maintain animal-welfare records.</p><p>Information on the website is provided for general awareness and coordination. It is not veterinary, medical, legal, financial or professional advice.</p></>],
  ['3. Rescue reports and emergencies', <><p>You may submit information about an injured, sick or distressed animal. We may review the report, contact you for clarification and decide whether and how we can respond based on urgency, location, resources, safety and animal-welfare priorities.</p><p>Submitting a report does not create a promise, contract or guarantee that LAHIT will attend, rescue, treat, transport or fund care. This website is not an emergency service. In an immediate danger or life-threatening situation, contact the appropriate local emergency, veterinary or animal-control service first.</p></>],
  ['4. Adoption and volunteer applications', <><p>Adoption applications and volunteer forms help our team assess suitability and coordinate next steps. Submission does not guarantee approval, placement, acceptance as a volunteer or any particular outcome. We may request additional information, conduct checks, or decline an application for welfare, safety, capacity or other legitimate reasons.</p><p>You agree to provide information that is accurate and current, to respond honestly to follow-up questions and to tell us if your circumstances change. You must not impersonate another person or submit information without permission.</p></>],
  ['5. Accounts and security', <><p>Some candidate and administrative features require an account. Keep your login details confidential, use a strong unique password and tell us promptly if you suspect unauthorised access. You are responsible for activity carried out through your account unless it resulted from our failure to take reasonable security measures.</p><p>We may suspend or remove access where necessary to protect animals, people, data, the website or the integrity of our records.</p></>],
  ['6. Acceptable use', <><p>You must not use the website to:</p><ul><li>submit false, misleading, abusive, discriminatory or harmful information;</li><li>upload malware, unlawful material or images that violate another person’s privacy or rights;</li><li>harass volunteers, applicants, adopters, staff or other users;</li><li>probe, disrupt, scrape, reverse engineer or attempt unauthorised access to the website or its systems; or</li><li>use the website for commercial solicitation, spam or any purpose unrelated to lawful animal-welfare activity.</li></ul><p>We may remove content, limit access or refer suspected unlawful conduct to the appropriate authority.</p></>],
  ['7. Content and intellectual property', <><p>LAHIT and its licensors own or control the website design, branding, text, graphics and other original material unless stated otherwise. You may view and share links for personal, non-commercial purposes, but you may not copy, modify, sell or republish our material without permission.</p><p>When you submit a photo, story or other content, you confirm that you have the right to share it. You give LAHIT a non-exclusive, royalty-free permission to store, review, reproduce and display that content for rescue coordination, animal-welfare communication and website administration. Contact us if you need us to review or remove submitted content.</p></>],
  ['8. Third-party services and links', <><p>The website may rely on third-party hosting, databases, authentication, image storage, email, maps, social platforms and other services. Their terms and policies may apply to your use of those services. We are not responsible for third-party websites, availability, content or actions.</p><p>Animal listings, rescue stories, statistics and other public information may change, contain errors or become unavailable. We do not promise that every page or service will always be current or uninterrupted.</p></>],
  ['9. Disclaimers and liability', <><p>To the extent permitted by law, the website and its content are provided on an “as available” basis. LAHIT does not guarantee that the website will be error-free, continuously available, or that a report, application or communication will produce a particular result.</p><p>Nothing in these terms excludes liability that cannot lawfully be excluded, including liability for fraud, deliberate misconduct or rights that apply to you under mandatory law. Subject to that limitation, LAHIT will not be responsible for indirect, incidental or consequential loss arising from use of the website or reliance on a submission response.</p></>],
  ['10. Changes, governing law and contact', <><p>We may update these terms as the website or our services change. The current version will be posted on this page with a new “Last updated” date. Continued use after an update means you accept the updated terms.</p><LegalContactDetails variant="terms" /></>],
];

export default function TermsPage() {
  return <main className="public-page min-h-screen bg-base-200"><Navbar /><section className="pt-32 pb-16 sm:pt-40 sm:pb-24"><Container size="md"><div className="mb-12 max-w-3xl"><span className="eyebrow text-secondary">Using LAHIT responsibly</span><h1 className="mt-6 text-4xl font-black tracking-[-0.055em] text-primary sm:text-6xl">Terms of Service</h1><p className="mt-5 text-lg leading-relaxed text-primary/65">The basic rules for using the LAHIT Animal Welfare website and submitting information to our team.</p><p className="mt-4 text-sm font-semibold uppercase tracking-[0.1em] text-primary/45">Last updated: 22 September 2026</p></div><div className="space-y-8 rounded-[2rem] border border-primary/10 bg-base-100 p-6 shadow-[0_12px_50px_rgba(11,51,36,0.06)] sm:p-10">{sections.map(([title, body]) => <section key={title} className="border-b border-primary/10 pb-8 last:border-b-0 last:pb-0"><h2 className="text-2xl font-black tracking-[-0.035em] text-primary">{title}</h2><div className="mt-4 space-y-4 leading-relaxed text-primary/70 [&_li]:ml-5 [&_li]:list-disc [&_ul]:space-y-2">{body}</div></section>)}</div><p className="mt-8 text-sm leading-relaxed text-primary/50">This page is a website terms draft based on the features currently present in the LAHIT application. It is not legal advice and should be reviewed with a qualified professional before publication.</p><Link href="/" className="mt-6 inline-flex font-bold text-primary underline decoration-primary/25 underline-offset-4">← Back to LAHIT</Link></Container></section><Footer /></main>;
}
