'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, Siren } from 'lucide-react';

const labels = { new: 'Received', reviewing: 'Reviewing', dispatched: 'Team dispatched', resolved: 'Resolved', dismissed: 'Closed' };
const classes = { new: 'bg-secondary/10 text-secondary', reviewing: 'bg-amber-500/10 text-amber-700', dispatched: 'bg-blue-500/10 text-blue-700', resolved: 'bg-success/15 text-green-800', dismissed: 'bg-primary/10 text-primary/55' };
function dateLabel(value) { return new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(new Date(value)); }

export default function ReportsPage() {
  const [reports, setReports] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { fetch('/api/candidate/reports/', { cache: 'no-store' }).then((response) => response.json()).then((result) => { if (!result.success) throw new Error(result.error); setReports(result.data); }).catch((loadError) => setError(loadError.message || 'Could not load reports.')); }, []);
  return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-secondary">Community response</p><h2 className="mt-2 text-3xl font-black tracking-[-0.055em] text-primary sm:text-4xl">My rescue reports</h2><p className="mt-2 max-w-xl text-sm leading-6 text-primary/55">See how the LAHIT team is progressing cases you have reported.</p></div><Link href="/candidate/reports/new/" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-full bg-secondary px-5 text-sm font-black text-white hover:bg-[#e85e3b]"><Siren className="h-4 w-4" /> Report an emergency</Link></div>{error && <div className="rounded-2xl bg-error/10 p-4 text-sm font-semibold text-error">{error}</div>}{!reports ? <div className="h-72 animate-pulse rounded-[2rem] bg-white/60" /> : reports.length === 0 ? <div className="rounded-[2rem] bg-white p-10 text-center shadow-sm"><Siren className="mx-auto h-10 w-10 text-primary/25" /><h3 className="mt-4 text-xl font-black text-primary">No reports yet</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-primary/55">If you find an injured or distressed animal, share the location and details with our response team.</p><Link href="/candidate/reports/new/" className="mt-6 inline-flex min-h-11 items-center gap-2 rounded-full bg-primary px-5 text-sm font-black text-white">Create a report <ArrowUpRight className="h-4 w-4" /></Link></div> : <div className="grid gap-4 lg:grid-cols-2">{reports.map((report) => <article key={report._id} className="rounded-[2rem] bg-white p-6 shadow-sm sm:p-7"><div className="flex items-start justify-between gap-4"><div><span className="text-xs font-black uppercase tracking-[0.14em] text-secondary">{report.animalType} report</span><h3 className="mt-2 text-xl font-black tracking-[-0.04em] text-primary">{report.location}</h3></div><span className={`shrink-0 rounded-full px-3 py-1 text-xs font-black ${classes[report.status] || 'bg-primary/10 text-primary'}`}>{labels[report.status] || report.status}</span></div><p className="mt-5 text-sm leading-6 text-primary/65">{report.description}</p><div className="mt-5 flex items-center justify-between border-t border-primary/10 pt-4 text-xs font-bold text-primary/45"><span>Reported {dateLabel(report.createdAt)}</span><span>{report.phone}</span></div></article>)}</div>}</div>;
}
